# Versão da sintaxe do docker-compose
version: '3.8'

services:

  # Container do Backend 
  backend:
    build: ./backend       
    container_name: cardapio-backend
    ports:
      - "5000:5000"        
    environment:
      - PORT=5000          # Variável de ambiente (substitui o .env em produção)
    restart: unless-stopped 

  # Container do Frontend 
  frontend:
    build: ./frontend      
    container_name: cardapio-frontend
    ports:
      - "8080:80"          # Porta 8080 do computador → Porta 80 do container
    depends_on:
      - backend            
    restart: unless-stopped